language: node_js
cache:
  npm: true
  directories:
    - /tmp/chromedriver/
node_js:
  - "8"
addons:
  chrome: stable
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: build
    - stage: check for updates
      if: branch IN (master) AND type IN (cron) AND fork = false
      script:
        - npm install chromedriver@76.0.1 --no-save
        - node ./op-update-watcher/checkVersionAndPush.js
    - stage: publish
      script: false
      if: branch IN (master) AND type IN (push, api) AND fork = false
      deploy:
        provider: script
        script:
          - npm run semantic-release
        skip_cleanup: true
        on:
          branch:
            - master
