name: Check Latest Version

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 12 * * *'

jobs:
  check-for-updates:
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node: ["10"]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v1.1.0
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: |-
          npm install && npm install chromedriver@$(node -p '/\d+/.exec(process.argv.slice(1).join(" "))[0]' $(google-chrome --version)) --no-save

      - name: Check
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
        run: node ./op-update-watcher/checkVersionAndPush.js
