name: Check Latest Version

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 12 * * *'

jobs:
  check-for-updates:
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node: ['18']

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Get Node Version
        run: |
          echo "NODE_VERSION=$(jq -r .engines.node package.json)" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm

      - name: Get pnpm store directory
        id: pnpm-store
        run: |
          echo "PNPM_STORE_DIR=$(pnpm store path)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.PNPM_STORE_DIR }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install

      - name: Check
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
        run: tsx ./op-update-watcher/checkVersionAndPush.ts
