name: Verify Downloads

on: [pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ['10']

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v1.1.0
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: npm install

      - name: Checks
        run: npm run check

      - name: Integration Tests
        run: npm run test

      - name: Integration Tests
        run: npm run integration
