name: Verify Downloads

on: [pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Get Node Version
        run: |
          echo "NODE_VERSION=$(jq -r .engines.node package.json)" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm

      - name: Get pnpm store directory
        id: pnpm-store
        run: |
          echo "PNPM_STORE_DIR=$(pnpm store path)" >> "$GITHUB_ENV"
          echo "PNPM_STORE_DIR=$(pnpm store path)" >> "$Env:GITHUB_ENV"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-store.outputs.name }}"
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install

      - name: Unit Tests
        run: pnpm jest

      - name: Integration Tests
        run: pnpm jest --integration
