name: Release

on:
  push:
    branches:
      - master
      - alpha

jobs:
  build-and-release:
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node: ['10']

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v1.1.0
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: npm install

      - name: Checks
        run: npm run check

      - name: Integration Tests
        run: npm run test

      - name: Integration Tests
        run: npm run integration

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
        run: npm run before-release && npm run release
